version: "3.1"
services:
  app_opensid:
    container_name: app_opensid
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: always
    depends_on:
      - php_opensid
    links:
      - php_opensid
    networks:
      - frontend
    ports:
      - 8000:8001
      - 8002:8002

    volumes:
      - ./html:/public_html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

  mysql-server-opensid:
    container_name: mysql-server-opensid
    image: "mariadb:10.3"
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data-opensid-mariadb:/var/lib/mysql
    networks:
      - db
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.50"
    restart: always

  php_opensid:
    container_name: php_opensid
    networks:
      - backend_opensid
      - frontend
      - db
    build:
      context: ./
      dockerfile: .docker/Dockerfile.php
    restart: always
    ports:
      - 9005:9000
    depends_on:
      - mysql-server-opensid
    volumes:
      - ./html:/public_html
      - ./.docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php.ini:/usr/local/etc/php/php.ini

volumes:
  mysql-data-opensid-mariadb:
    external: false

networks:
  frontend:
  backend_opensid:
    name: backend_opensid
    driver: bridge
  db:
    name: db
    driver: bridge
